### ISSUE TITLE
Modelado de la BD

### ISSUE THREAD

**Issue by 05K4R1N** [05K4R1N/Instituto-de-Ensenianza-Superior#1]
Franklin necesito ayuda para que me ayudes a completar el modelado de la BD... checa si hice bien  de acuerdo con el enunciado del problema por fa...
Ojo que lo hice en workbench de acuerdo a tus especificaciones :v

**Comment by 05K4R1N** [comment]
Franklin termine con el modelado, no se si vos estas de acuerdo a como lo hice. Checa por favor y si tienes duda por favor desde aca te respondere :)

**Comment by nogardark** [comment]
esta bien el modelo segun el problema :D ya segun vayamos programando encontraremos dificultad si esq la hay en el modelo pero por ahora nos quedaremos con este modelo...

**Comment by 05K4R1N** [comment]
Ok, entonces quedamos a que la BD de datos llegara estar sujeto  a Prueba y Error. Lo convertire en script y lo subire, ya que manejaremos Postgres, existe el temor de que el Script no se ajuste al pgadmin asi que lo chequeare y si no da, lo voy a rehacer en powerdesigner

**Comment by nogardark** [comment]
ok bro.....de ahi tenemos q realizar las tareasss por cierto utilizaremos alguna metodologia de desarrollo... aalguna agil talves??

**Comment by 05K4R1N** [comment]
como cual sugieres? yo digo simplemente viejo, hacer lo que hay que hacer y si hay idea hacerla simplemente, antes pero notificar desde aca sobre alguna idea que se sugiere o algo para que yo este enterado o tu

**Comment by 05K4R1N** [comment]
Lo comun yo diria, hacer MVC :3

**Comment by nogardark** [comment]
me referia a una metodologia de desarrollo.....no a un patron

**Comment by 05K4R1N** [comment]
sorry.. cual sugieres?

**Comment by nogardark** [comment]
en este caso seria el scrum ya q el xp es en parejas y no siempre estaremos reuniendonos, cual sugieres tu otra agil talves q se adecue a nuestra forma q se adapte al trabajo q estamos haciendo

**Comment by 05K4R1N** [comment]
si a la mierda, scrum que sea :v

**Comment by 05K4R1N** [comment]
Ahora espero que sepas usar bien Ramas en el repositorio, no quiero que hagas commits directos al master, porque asi nos evitamos de problemas con el reposiorio...
Propongo hacer ramas por funcionalidad

**Comment by nogardark** [comment]
es la forma mas adecuada...ramas por funcionalidad :+1:

**Comment by 05K4R1N** [comment]
listo bro... ya sabes entonces
Ramas por funcionalidad
Cualquier duda, novedad, idea o pregunta desde aca hay que notificar
Cuando puedas haz el proyecto tampoco exijo demasiado, 1 commit por semana al menos bro

**Comment by nogardark** [comment]
listo

**Comment by nogardark** [comment]
relize la coneccion a la base de datos postgres en el proyecto estan las especificiones de coneccion el nombre de la base de datos usuario y contraseña

**Comment by 05K4R1N** [comment]
mmmm ok bro lo voy a chequear haciendole pull :3
