### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by nogardark** [05K4R1N/Instituto-de-Ensenianza-Superior#3]
los nombres de tus variables no son audescriptivos, existe codigo repetido,, se puede optimizar o refactorizar, de lo estructural a un no lo vi , tener un modelo de diseño de objetos... como hacen los arquitectos  primero se diseña... seria bueno. y trata de usar menos if..... los metodos solo deben hacer solo una cosa... solo uno si hay q validar algo asignar a otro metodo q haga solo eso..
 y lo mas importante no existe test unit.... se q insisto con esto de los test pero es muy importante q inicies con TDD te daras cuenta q tu codigo se reducira y sera mas entendible... por ahora fue facil eliminar tus bugs pero a medida q tu proyecto vaya creciendo te sera mas dificil eliminarlos e incluso localizarlos....y programa pensando q otras personas lo leeran tu proyecto 
bueno bro para la primera version esta bien podemos mejorarlo....

**Comment by 05K4R1N** [comment]
ok primero necesito saber en que clases hay código repetido para poder reducir el código por favor....
